[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_solc = true
fs_permissions = [
  { access = "read-write", path = "./addresses/" },
  { access = "read", path = "./script/input/" },
  { access = "read-write", path = "./script/output/" }
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config